import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
        <img src="" alt="" />
        <a href="/">Home</a>
        <a href="/events">Events</a>
        <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        <a href="">
          <img src="" alt="" />
          <h2>Events in London</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus ratione temporibus cumque, praesentium quod quia voluptatum laborum, consequuntur earum accusantium, beatae aperiam ducimus perferendis repellat nihil provident ullam repudiandae illum.</p>
        </a>

        <a href="">
          <img src="" alt="" />
          <h2>Events in San Francisco</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus ratione temporibus cumque, praesentium quod quia voluptatum laborum, consequuntur earum accusantium, beatae aperiam ducimus perferendis repellat nihil provident ullam repudiandae illum.</p>
        </a>

        <a href="">
          <img src="" alt="" />
          <h2>Events in Barcelona</h2>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus ratione temporibus cumque, praesentium quod quia voluptatum laborum, consequuntur earum accusantium, beatae aperiam ducimus perferendis repellat nihil provident ullam repudiandae illum.</p>
        </a>
      </main> 

      <footer className={styles.footer}>
        <p>2023 time to code</p>
      </footer> 
    </> 
  )
}
